### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by gh0stpwner** [apognu/htb#1]
Hey brother i was trying to test your project but can't finnish the the compilation. 

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name htb src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=9e7ec8df320844e7 -C extra-filename=-9e7ec8df320844e7 --out-dir /root/Desktop/htb/target/debug/deps -C incremental=/root/Desktop/htb/target/debug/incremental -L dependency=/root/Desktop/htb/target/debug/deps --extern async_trait=/root/Desktop/htb/target/debug/deps/libasync_trait-5b77dd693aec9f07.so --extern chrono=/root/Desktop/htb/target/debug/deps/libchrono-d1535ce2f2a2e306.rlib --extern clap=/root/Desktop/htb/target/debug/deps/libclap-75f1ade2224487e8.rlib --extern colored=/root/Desktop/htb/target/debug/deps/libcolored-fc11fc889a2cb4e6.rlib --extern dirs=/root/Desktop/htb/target/debug/deps/libdirs-82358ec6a2bb09ee.rlib --extern htmlescape=/root/Desktop/htb/target/debug/deps/libhtmlescape-8423010996da3c0b.rlib --extern lazy_static=/root/Desktop/htb/target/debug/deps/liblazy_static-c9fdb400200e9c0f.rlib --extern libnotify=/root/Desktop/htb/target/debug/deps/liblibnotify-a1aa7b43f70dd016.rlib --extern linefeed=/root/Desktop/htb/target/debug/deps/liblinefeed-23c753c348415dc1.rlib --extern prettytable=/root/Desktop/htb/target/debug/deps/libprettytable-afa2c98cc54665a7.rlib --extern reqwest=/root/Desktop/htb/target/debug/deps/libreqwest-9649a21db07210c4.rlib --extern serde=/root/Desktop/htb/target/debug/deps/libserde-7b3541c86760eaa7.rlib --extern serde_json=/root/Desktop/htb/target/debug/deps/libserde_json-3186e4349102708d.rlib --extern termion=/root/Desktop/htb/target/debug/deps/libtermion-dd10fceb16871e66.rlib --extern tokio=/root/Desktop/htb/target/debug/deps/libtokio-5d40765f7bfce4a5.rlib -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu` (exit code: 1)

**Comment by apognu** [comment]
Hi!

Did you compile with `cargo build`? The first thing that comes to mind is if you are on Rust's stable channel. This crate requires the `nightly` channel to compile. Tell me if that fixes your build.

Build instructions is something that is missing from the README. I'll update it as soon as I can.

**Comment by apognu** [comment]
I'll consider this fixed pending any other comment from you.
